# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b34f0227c81bb3b29bf776c1e5d37f70"
application_url = "https://salmon-enlargement-banana-hung.trycloudflare.com"
embedded = true
name = "Order Print Amura"
handle = "order-print-amura"

[build]
dev_store_url = "ga4-setup.myshopify.com"
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_customers"

[auth]
redirect_urls = [
  "https://salmon-enlargement-banana-hung.trycloudflare.com/auth/callback",
  "https://salmon-enlargement-banana-hung.trycloudflare.com/auth/shopify/callback",
  "https://salmon-enlargement-banana-hung.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
